### ISSUE TITLE
Tempfile isn't deleted if Mix task is force quit

### ISSUE THREAD

**Issue by kieraneglin** [kieraneglin/encrypted_secrets_ex#1]
In order to edit secrets, we have to decrypt the existing secrets and save them to disk first.  If the Mix task is force quit, the tempfile is not removed.

This is a problem because the unencrypted tempfile could be checked into VCS if you're not careful which could expose your secrets.

With ruby, you can catch `Interrupt` events and run your cleanup code after.  I am not aware of a similar mechanism in Elixir, so I'll need to explore that.

**Comment by kipcole9** [comment]
A couple of thoughts (not with any great authority though):

1. Store the tempfile outside the source tree, in `/tmp`. On some systems this is a directory that isn't stored on disk (it uses [tmpfs](http://man7.org/linux/man-pages/man5/tmpfs.5.html)) which is an added benefit. Either way it won't end up in VCS although there is still the risk of persisting the unencrypted secrets - although a lower risk if on `/tmp`

2. Look at [trapping exits](http://erlang.org/doc/reference_manual/processes.html#receiving-exit-signals) and see if that helps.  I note this is considered an uncommon thing to do which, after some googling, appears to need careful handling

3. Consider never persisting the unencrypted secrets and only allow editing via `iex` and some helper methods in your library.  Not as easy to edit the secrets maybe, but easier to assure that there are never unencrypted secrets persisted to disk

**Comment by kieraneglin** [comment]
@kipcole9 Thank you for the input! I really like the first option and was thinking of something similar yesterday. 

I'm a little bit out of my depth here, but I wonder if it's possible to load the decrypted contents of the file into memory and have the editors "open" that - avoiding writing the decrypted secrets to disk whatsoever. 

Either way, I appreciate the suggestions and will start working on something soon!
